# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 05:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('healthcheck_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=200)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('name', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('nodes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Host'),
        ),
        migrations.AddField(
            model_name='context',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Pool'),
        ),
    ]
