# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('name', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Monitor'),
        ),
    ]
