# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170908_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='healthcheck_url',
        ),
    ]
