# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_context_healthcheck_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Context')),
            ],
        ),
    ]
