# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170916_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='context',
        ),
        migrations.RemoveField(
            model_name='version',
            name='app',
        ),
        migrations.AddField(
            model_name='context',
            name='app_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='context',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Context'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
