# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170916_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_string',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='context',
        ),
        migrations.AddField(
            model_name='version',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Context', to_field='app_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='context',
            name='app_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
