# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170917_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.App'),
            preserve_default=False,
        ),
    ]
