# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 18:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170917_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
